version: 2
updates:
  - package-ecosystem: "gradle" 
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
    groups:
      deps:
        patterns:
          - "*"
