/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "tabour"

include("core", "proto", "spring", "plug")

val kotlinVersion = "2.0.21"
val coroutinesVersion = "1.9.0"
val testContainersVersion = "1.20.2"
val awaitilityVersion = "4.2.2"

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            library(
                "kotlin-coroutines",
                "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion",
            )
            library(
                "kotlin-coroutines-jdk",
                "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:$coroutinesVersion",
            )
            library("aws-sqs", "software.amazon.awssdk:sqs:2.28.26")
        }

        create("testLibs") {
            library("kotlin-test-junit", "org.jetbrains.kotlin:kotlin-test-junit5:$kotlinVersion")
            library("kotlin-test-main", "org.jetbrains.kotlin:kotlin-test:$kotlinVersion")
            library("mockk", "io.mockk:mockk:1.13.13")
            library(
                "kotlin-test-coroutines",
                "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion",
            )

            library(
                "testcontainers-localstack",
                "org.testcontainers:localstack:$testContainersVersion",
            )
            library(
                "testcontainers-core",
                "org.testcontainers:testcontainers:$testContainersVersion",
            )
            library("awaitility-core","org.awaitility:awaitility:$awaitilityVersion")
            library("awaitility-kotlin","org.awaitility:awaitility-kotlin:$awaitilityVersion")

            bundle("kotlin-test", listOf("kotlin-test-main", "kotlin-test-junit"))
            bundle("testcontainers", listOf("testcontainers-core", "testcontainers-localstack"))
            bundle("awaitility", listOf("awaitility-kotlin", "awaitility-core"))
        }
    }
}
