/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "tabour"

include("core", "proto", "spring", "ktor")

dependencyResolutionManagement {
    versionCatalogs { create("testLibs") { from(files("gradle/testLibs.versions.toml")) } }
}
