/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "1.8.20"
//    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()

    maven { url = uri("https://repo.maven.apache.org/maven2/") }
}

dependencies {
    //    api("org.springframework.boot:spring-boot-autoconfigure:2.5.0")
    //    api("org.springframework.boot:spring-boot-configuration-processor:2.5.0")
    api(libs.kotlin.jdk8)
    api(libs.kotlin.coroutines)
    api(libs.kotlin.coroutines.jdk)
    api(libs.aws.sqs)
//    api("")
    //    api("javax.annotation:javax.annotation-api:1.3.2")
    //    api("org.jetbrains.kotlin:kotlin-reflect:1.6.0")
    //    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.0")
    //    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0")
    //    api("io.github.microutils:kotlin-logging-jvm:2.1.21")
//    api("com.google.protobuf:protobuf-java-util:3.21.1")
    //    api("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.5.2")
    //    api("org.apache.httpcomponents:httpcore:4.4.15")
    testImplementation("io.mockk:mockk:1.13.4")
    testImplementation("io.kotest:kotest-assertions-core-jvm:5.0.2")
    testImplementation("org.testcontainers:testcontainers:1.17.2")
    testImplementation("org.testcontainers:junit-jupiter:1.16.2")
    //    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
    testImplementation(testLibs.bundles.kotlin.test)
    //    compileOnly("org.springframework:spring-context-support:5.3.7")
}

group = "com.katanox"

version = "0.3.0"

description = "Tabour Core"


kotlin {
    jvmToolchain(19)
    sourceSets.all {
        languageSettings {
            languageVersion = "2.0"
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

//java { withSourcesJar() }

publishing { publications.create<MavenPublication>("maven") { from(components["java"]) } }
